version: "3.9"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      POSTGRES_SERVER: db
      POSTGRES_DB: prompts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
  
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      VUE_APP_PROMPTS_API_BASE_URL: http://127.0.0.1:8000
  
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: prompts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
